### PR TITLE
Use map, reduce instead of double forEach

### PR DESCRIPTION
**Pull request by cokencode**
When I was reading the code to figure out how 'webpack-node-externals' works, I came up with idea that map, reduce methods are better than double forEach to get the dependencies from package.json.
I'm a beginner in Javascript. I'm open to other suggestions and happy to learn more from it:D

### CODE REVIEW

**Comment by chrisblossom** [comment]
@cokencode here are a couple alternatives that encapsulate the whole function inside one reduce.  Not sure which one is better/more correct, just throwing it out there for you.

Also, it looks like the original code is not tested (unless I skipped over the test, which is possible). Usually it is a good idea to include tests with your PR that pass for both the new and old code, especially if it is for a code optimization. Just my 2 cents.

```js
// es5
var deps = sections.reduce(function (acc, section) {
  var packages = Object.keys(packageJson[section])
    .map(function (dependency) {
      return dependency;
    });

  return acc.concat(packages);
}, []);
```

```js
// es6
const deps = sections.reduce((acc, section) => {
  const packages = Object.keys(packageJson[section])
    .map(dependency => dependency);

  return acc.concat(packages);
}, []);
```

**Comment by cokencode** [comment]
@chrisblossom Thanks for your suggestions. It was just code optimization, and I used the test that already set up for old code to test new code. (I'm not sure if the old code was tested. I probably didn't check the test carefully)

Coming back to the code, I like your suggestion that it encapsulates whole function inside one reduce. If I made a change in it, I would remove `.map(function (dependency){ return dependency })` which is basically returning the same array.

```javascript
var deps = sections.reduce(function (acc, section) {
  var pakages = Object.keys(packageJson[section]);
  
  return acc.concat(packages);
};
```

**Comment by liady** [comment]
@cokencode @chrisblossom thank you for your proposals. The reason I chose to use an object is to avoid cases of duplicate dependencies (i.e same dependency listed in both 'devDependencies' and 'peerDependencies'). Concatenating those arrays will cause this dependency to appear twice, while building an object will prevent it.
It doesn't seem that there is a substantial performance gain, but I'm open to any PRs that will make the code more elegant :)
What do you think?

**Comment by cokencode** [comment]
@liady I didn't consider the case of duplicate dependencies. It's my mistake. How about using filter method to avoid duplicate dependencies?

```javascript
var deps = [];
sections.forEach(function (section){
  var packages = Object.keys(packageJson[section] || {});

  packages = packages.filter(function (pkg){
    return deps.indexOf(pkg) == -1
  }

  deps = deps.concat(packages);
});
```

**Comment by liady** [comment]
@cokencode Filtering duplicates from an array is an O(n^2) operation, and its less performant than storing them in an hash table (which is ~O(1)), and then extracting the keys (which is O(n)).

I'm open to any PR that will keep the same runtime performance of the code :)

**Comment by cokencode** [comment]
@liady Thanks for your kind explanation. Based on your explanation, the new code clearly has more expensive operation. As I can't come up with better idea now, I will close this PR. I've learned more from the conversation in this PR. Thanks again.

**Pull request closed without merging**
